// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Configuration;
using EncriptaDesencriptaCadena;
using Microsoft.EntityFrameworkCore;

namespace EtiquetasTransferencias.EtiquetasModels;

public partial class ESCORIALContext : DbContext
{
    public ESCORIALContext()
    {
    }
    public ESCORIALContext(DbContextOptions<ESCORIALContext> options)
        : base(options)
    {
    }
    public virtual DbSet<EscoTxEstado> EscoTxEstado { get; set; }
    public virtual DbSet<EscoTxEtiqueta> EscoTxEtiqueta { get; set; }
    public virtual DbSet<producto> producto { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            string connectionString = Crypto.Decrypt(ConfigurationManager.ConnectionStrings["Escorial"].ConnectionString);
            optionsBuilder.UseNpgsql(connectionString);
        }
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("fuzzystrmatch")
            .HasPostgresExtension("hstore")
            .HasPostgresExtension("ltree")
            .HasPostgresExtension("pg_stat_statements")
            .HasPostgresExtension("pgstattuple")
            .HasPostgresExtension("unaccent");
        modelBuilder.Entity<EscoTxEstado>(entity =>
        {
            entity.HasKey(e => e.id).HasName("EscoTxEstado_pkey");
            entity.ToTable("EscoTxEstado", "web");
            entity.Property(e => e.id).UseIdentityAlwaysColumn();
            entity.Property(e => e.codigo).HasColumnType("character varying");
            entity.Property(e => e.descripcion).HasColumnType("character varying");
        });
        modelBuilder.Entity<EscoTxEtiqueta>(entity =>
        {
            entity.HasKey(e => e.id).HasName("EscoTxEtiqueta_pkey");
            entity.ToTable("EscoTxEtiqueta", "web");
            entity.Property(e => e.id).UseIdentityAlwaysColumn();
            entity.Property(e => e.codigo).HasColumnType("character varying");
            entity.Property(e => e.fecha).HasColumnType("timestamp without time zone");
        });
        modelBuilder.Entity<producto>(entity =>
        {
            entity.HasKey(e => e.id).HasName("producto_pkey");
            entity.HasIndex(e => e.bo_place_id, "idx00344081");
            entity.HasIndex(e => e.codigo, "idx00344082");
            entity.HasIndex(e => e.rubro_id, "idx00344083");
            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.activestatus).HasDefaultValue(0);
            entity.Property(e => e.alto)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.ancho)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.bienuso).HasDefaultValue(false);
            entity.Property(e => e.calculoexinolineal).HasDefaultValue(false);
            entity.Property(e => e.cantidad).HasDefaultValue(0);
            entity.Property(e => e.cateant).HasMaxLength(10);
            entity.Property(e => e.categoria).HasMaxLength(10);
            entity.Property(e => e.checksoptimisticupdates).HasMaxLength(40);
            entity.Property(e => e.codigo).HasMaxLength(30);
            entity.Property(e => e.concatcodprod).HasDefaultValue(false);
            entity.Property(e => e.creacioncodalt).HasDefaultValue(false);
            entity.Property(e => e.descripcion).HasMaxLength(150);
            entity.Property(e => e.esmultiplodebultos).HasDefaultValue(false);
            entity.Property(e => e.espesor)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.existenciaobligatoria).HasDefaultValue(false);
            entity.Property(e => e.existenciaobligatorianl).HasDefaultValue(false);
            entity.Property(e => e.explotapropiedades).HasDefaultValue(false);
            entity.Property(e => e.explotaserieeninventario).HasDefaultValue(false);
            entity.Property(e => e.external_id).HasMaxLength(10);
            entity.Property(e => e.fechacategoria).HasMaxLength(17);
            entity.Property(e => e.fechavencimientocondicion).HasMaxLength(8);
            entity.Property(e => e.kit).HasDefaultValue(false);
            entity.Property(e => e.lineascodigos).HasMaxLength(240);
            entity.Property(e => e.momento).HasMaxLength(17);
            entity.Property(e => e.montoproducto)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.montototal)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.peso)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.porcentajecategoria)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.porcentajereposicion)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.puntopedido)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.stockmaximo)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.stockminimo)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.stockoptimo)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.stockseguridad)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.ultimamodificacion).HasMaxLength(17);
            entity.Property(e => e.unidadesporbulto)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.unidminimcomer)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
            entity.Property(e => e.usuario).HasMaxLength(30);
            entity.Property(e => e.utilcnltotalitem).HasDefaultValue(false);
            entity.Property(e => e.utilizacantidadnolineal).HasDefaultValue(false);
            entity.Property(e => e.utilizaseriedetallada).HasDefaultValue(false);
            entity.Property(e => e.volumen)
                .HasPrecision(22, 10)
                .HasDefaultValueSql("0.0");
        });
        modelBuilder.HasSequence("aux_suceso_inc_seq");
        modelBuilder.HasSequence("hibernate_sequence", "web");
        OnModelCreatingPartial(modelBuilder);
    }
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}