// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtiquetasTransferencias.EtiquetasModels;

public partial class EscoTxEtiqueta
{
    public int id { get; set; }

    public string codigo { get; set; }

    public Guid? producto_id { get; set; }

    public decimal? cantidad { get; set; }

    public DateTime? fecha { get; set; }

    public int? estado_id { get; set; }
}