// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtiquetasTransferencias.EtiquetasModels;

public partial class EscoTxEstado
{
    public int id { get; set; }

    public string codigo { get; set; }

    public string descripcion { get; set; }
}