// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EtiquetasTransferencias.EtiquetasModels;

#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
public partial class producto
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
{
    public Guid id { get; set; }

    public int? activestatus { get; set; }

    public string checksoptimisticupdates { get; set; }

    public string codigo { get; set; }

    public Guid? segmento_id { get; set; }

    public string descripcion { get; set; }

    public string usuario { get; set; }

    public string momento { get; set; }

    public Guid? catalogo_id { get; set; }

    public Guid? itemcatalogo_id { get; set; }

    public Guid? codigosalternativos_id { get; set; }

    public Guid? detalleproveedores_id { get; set; }

    public Guid? listacosto_id { get; set; }

    public Guid? grupocomposicion_id { get; set; }

    public Guid? rubro_id { get; set; }

    public Guid? posicionadorimpuestos_id { get; set; }

    public Guid? partidapresup_id { get; set; }

    public Guid? tipodistribuciondefault_id { get; set; }

    public Guid? composicion_id { get; set; }

    public Guid? clasificacioncosto_id { get; set; }

    public Guid? boextension_id { get; set; }

    public Guid? componentecosto_id { get; set; }

    public Guid? definicioncompcosto_id { get; set; }

    public Guid? tipoobjetoestatico_id { get; set; }

    public Guid? flag_id { get; set; }

    public Guid? transicion_id { get; set; }

    public Guid? centrocostos_id { get; set; }

    public Guid? centroscostosasociados_id { get; set; }

    public Guid? conceptooaf_id { get; set; }

    public Guid? unidadoperativa_id { get; set; }

    public Guid? distribucionproveedores_id { get; set; }

    public Guid? partidapresupventas_id { get; set; }

    public Guid? itemsesquemaoperativo_id { get; set; }

    public Guid? bocsf_id { get; set; }

    public Guid? numerador_id { get; set; }

    public Guid? relacionimpproductoservicio_id { get; set; }

    public Guid? condicion_id { get; set; }

    public string fechavencimientocondicion { get; set; }

    public string ultimamodificacion { get; set; }

    public Guid? bo_place_id { get; set; }

    public Guid? bo_owner_id { get; set; }

    public Guid? unidadmedida_id { get; set; }

    public Guid? unidadmedidanolineal_id { get; set; }

    public Guid? unidadesmedidaparticulares_id { get; set; }

    public decimal? unidminimcomer { get; set; }

    public Guid? equivalenciasparticulares_id { get; set; }

    public Guid? unidadesdeexpresion_id { get; set; }

    public Guid? tipoextraccion_id { get; set; }

    public Guid? grupospertenecia_id { get; set; }

    public Guid? datoscomplementarios_id { get; set; }

    public Guid? compania_id { get; set; }

    public Guid? atributosfusion_id { get; set; }

    public bool? existenciaobligatoria { get; set; }

    public decimal? unidadesporbulto { get; set; }

    public bool? esmultiplodebultos { get; set; }

    public Guid? configuradorimportacion_id { get; set; }

    public string external_id { get; set; }

    public bool? utilizacantidadnolineal { get; set; }

    public Guid? equivalenciasparticulnoli_id { get; set; }

    public Guid? unidadesmedidaparticulnoli_id { get; set; }

    public Guid? unidadesdeexpresionnoli_id { get; set; }

    public Guid? proveedores_id { get; set; }

    public bool? existenciaobligatorianl { get; set; }

    public bool? calculoexinolineal { get; set; }

    public Guid? tolerancia_id { get; set; }

    public Guid? numeradoresserie_id { get; set; }

    public bool? explotaserieeninventario { get; set; }

    public Guid? numeradoreslote_id { get; set; }

    public Guid? numeradoresdespacho_id { get; set; }

    public decimal? peso { get; set; }

    public decimal? volumen { get; set; }

    public bool? bienuso { get; set; }

    public decimal? stockminimo { get; set; }

    public decimal? puntopedido { get; set; }

    public decimal? stockseguridad { get; set; }

    public Guid? clientes_id { get; set; }

    public Guid? descriptor_id { get; set; }

    public Guid? especificacionbase_id { get; set; }

    public Guid? especificaciones_id { get; set; }

    public bool? explotapropiedades { get; set; }

    public Guid? productossustitutos_id { get; set; }

    public int? cantidad { get; set; }

    public bool? kit { get; set; }

    public decimal? stockmaximo { get; set; }

    public decimal? stockoptimo { get; set; }

    public decimal? alto { get; set; }

    public Guid? unidadmedidaalto_id { get; set; }

    public decimal? ancho { get; set; }

    public Guid? unidadmedidaancho_id { get; set; }

    public decimal? espesor { get; set; }

    public Guid? unidadmedidaespesor_id { get; set; }

    public Guid? unidadmedidavolumen_id { get; set; }

    public Guid? scriptpolinomicocosto_id { get; set; }

    public Guid? envasepredeterminado_id { get; set; }

    public Guid? envasespermitidos_id { get; set; }

    public Guid? lineas_id { get; set; }

    public string lineascodigos { get; set; }

    public bool? utilcnltotalitem { get; set; }

    public Guid? dimensiones_id { get; set; }

    public Guid? tipoamortizacion_id { get; set; }

    public decimal? porcentajereposicion { get; set; }

    public Guid? cuentascontables_id { get; set; }

    public Guid? cuentascontables2_id { get; set; }

    public Guid? cuentascontables3_id { get; set; }

    public Guid? cuentascontables4_id { get; set; }

    public Guid? cuentascontables5_id { get; set; }

    public Guid? cuentascontables6_id { get; set; }

    public Guid? cuentascontables7_id { get; set; }

    public Guid? cuentascontables8_id { get; set; }

    public Guid? cuentascontables9_id { get; set; }

    public Guid? cuentascontables10_id { get; set; }

    public string svg { get; set; }

    public Guid? numeradorescodalt_id { get; set; }

    public bool? creacioncodalt { get; set; }

    public bool? concatcodprod { get; set; }

    public string categoria { get; set; }

    public string cateant { get; set; }

    public decimal? montoproducto { get; set; }

    public decimal? montototal { get; set; }

    public decimal? porcentajecategoria { get; set; }

    public string fechacategoria { get; set; }

    public bool? utilizaseriedetallada { get; set; }
}