//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtiquetasTransferencias.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Impresora {
            get {
                return ((string)(this["Impresora"]));
            }
            set {
                this["Impresora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^XA \\n ^FO20,30^A0N,40,38^FDDesc: #DESCRIPCION#^FS \\n ^FO20,90^A0N,40,38^FDCodigo" +
            ": #CODIGO#^FS \\n ^FO20,150^A0N,40,38^FDCantidad: #CANTIDAD# U.^FS \\n ^FO100,260^" +
            "BY3 \\n ^BCN,200,Y,N,N,N \\n ^FD#CODIGOETIQUETA#^FS \\n ^XZ")]
        public string ZplEtiqueta {
            get {
                return ((string)(this["ZplEtiqueta"]));
            }
            set {
                this["ZplEtiqueta"] = value;
            }
        }
    }
}
